abstract class TaskStates {}
class InitialState extends TaskStates{}
class ChangeNavigationBarState extends TaskStates{}
class OpenBottomsheet extends TaskStates{}
class ShowDetails extends TaskStates{}
class ShowProgressInicator extends TaskStates{}
class CloseBottomsheet extends TaskStates{}
class CreatDB extends TaskStates{}
class InsertToDB extends TaskStates{}
class UbdateDB extends TaskStates{}
class GetFromDB extends TaskStates{}